sign_up/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView
from sign_up.views import *

urlpatterns = [
  url(r'^sign-up/', TemplateView.as_view(template_name="sign_up/sign_up.html"), name='sign_up'),
]

sign_up/models.py
from django.db import models
from modelcluster.fields import ParentalKey

from wagtail.contrib.forms.models import AbstractEmailForm, AbstractFormField
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, MultiFieldPanel, FieldRowPanel
from wagtail.core.fields import RichTextField, StreamField


class FormField(AbstractFormField):
  page = ParentalKey('SignUpPage', related_name='form_fields')

class ResetPasswordFormField(AbstractFormField):
  page = ParentalKey('ResetPasswordPage', related_name='form_fields')


class SignUpPage(AbstractEmailForm):
  agreement_message = RichTextField(null=True, blank=True)
  content_panels = AbstractEmailForm.content_panels + [
    InlinePanel('form_fields', label="Form fields"),
    FieldPanel('agreement_message'),
    MultiFieldPanel([
      FieldRowPanel([
        FieldPanel('from_address', classname="col6"),
        FieldPanel('to_address', classname="col6"),
      ]),
      FieldPanel('subject'),
    ], "Email"),
  ]

  def get_context(self, request):
    context = super().get_context(request)
    return context


class ResetPasswordPage(AbstractEmailForm):
  content_panels = AbstractEmailForm.content_panels + [
    InlinePanel('form_fields', label="Form fields"),
    MultiFieldPanel([
      FieldRowPanel([
        FieldPanel('from_address', classname="col6"),
        FieldPanel('to_address', classname="col6"),
      ]),
      FieldPanel('subject'),
    ], "Email"),
  ]

  def get_context(self, request):
    context = super().get_context(request)
    return context
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
from modelcluster.fields import ParentalKey
from wagtail.core.models import Orderable
from modelcluster.models import ClusterableModel
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime

class AddressContactDetails(models.Model):
  contact_person_name=models.TextField(null=True, blank=True)
  contact_person_phone=models.CharField(null=True, blank=True, max_length=500)
  contact_person_email=models.EmailField(null=True, blank=True)


class Address(Orderable, models.Model):  
  name = models.TextField(null=True, blank=True)
  profile = ParentalKey('Profile', related_name='address', null=True, blank=True)
  contact_details=models.OneToOneField(AddressContactDetails, on_delete=models.CASCADE, null=True)
  street_bldg=models.TextField(null=True, blank=True)
  barangay=models.TextField(null=True, blank=True)
  city=models.TextField(null=True, blank=True)
  province = models.TextField(null=True, blank=True)
  region_state=models.TextField(null=True, blank=True)
  country=models.TextField(null=True, blank=True)
  postal_code=models.IntegerField(null=True, blank=True)

class ShippingInformation(models.Model):
  userId = models.CharField(null=True, blank=True, max_length=500)
  username = models.CharField(null=True, blank=True, max_length=500)
  contact_person_phone=models.CharField(null=True, blank=True, max_length=500)
  contact_person_email=models.EmailField(null=True, blank=True)
  label = models.CharField(null=True, blank=True, max_length=500)
  address = models.OneToOneField(Address, on_delete=models.CASCADE, null=True)

class BusinessDetails(models.Model):  
  company_name=models.TextField(null=True, blank=True)
  business_address=models.OneToOneField(Address, on_delete=models.CASCADE, null=True)
  business_tin=models.TextField(null=True, blank=True)
  business_registration_number=models.TextField(null=True, blank=True)

class ShopDetails(models.Model):  
  shop_name=models.TextField(null=True, blank=True)
  holiday_mode=models.BooleanField(default=False)
  start_date=models.DateField(default=datetime.now, blank=True, null=True)
  start_time=models.TimeField(default=datetime.now, blank=True, null=True)
  end_date=models.DateField(default=datetime.now, blank=True, null=True)
  end_time=models.TimeField(default=datetime.now, blank=True, null=True)

class SellerDetails(models.Model):  
  seller_id=models.CharField(null=True, blank=True, max_length=500, unique=True)
  seller_status=models.CharField(null=True, blank=True, max_length=500)
  name_on_id=models.TextField(null=True, blank=True)
  id_type=models.TextField(null=True, blank=True)
  upload_id_front=models.ImageField(
    upload_to='documents',
    null=True,
    blank=True,
    help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.'
  )
  upload_id_front_url=models.TextField(null=True, blank=True)
  upload_id_back=models.ImageField(
    upload_to='documents',
    null=True,
    blank=True,
    help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.'
  )
  upload_id_back_url=models.TextField(null=True, blank=True)
  email=models.EmailField(null=True, blank=True)
  phone=models.TextField(null=True, blank=True)
  has_agreed_to_terms=models.BooleanField(default=False)
  shop_details=models.OneToOneField(ShopDetails, on_delete=models.CASCADE, null=True)

class Profile(ClusterableModel):
  birthday = models.DateField(default=datetime.now)
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  seller_details=models.OneToOneField(SellerDetails, on_delete=models.CASCADE, null=True)
  business_details=models.ForeignKey(BusinessDetails, models.DO_NOTHING, blank=True, null=True)
  pickup_address=models.ForeignKey(Address, models.DO_NOTHING, blank=True, null=True, related_name='pickup_address')
  return_address=models.ForeignKey(Address, models.DO_NOTHING, blank=True, null=True, related_name='return_address')
  def save(self, *args, **kwargs):
    self.id = self.user_id
    super(Profile, self).save(*args, **kwargs)

class Documents(models.Model):  
  profile=ParentalKey('Profile', related_name='document', null=True, blank=True)
  document_type=models.TextField(null=True, blank=True)
  document_url=models.TextField(null=True, blank=True)
  document=models.ImageField(
    upload_to='documents',
    null=True,
    blank=True,
    help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.'
  )

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
  if created:
      Profile.objects.create(user=instance)

sign_up/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth.hashers import make_password

from users.models import Profile
from sign_up.models import SignUpPage
from base.aws_client import AuthClient
from base.aws_client import ApiGatewayClient

import requests


def showErrorMessage(request, message):
    messages.error(request, message)
    self = SignUpPage.objects.get(slug='sign')
    return render(request, 'sign_up/sign_up_page.html', {
        'self': self,
    })


def showInfoMessage(request, message):
    messages.info(request, message)
    self = SignUpPage.objects.get(slug='sign')
    return render(request, 'sign_up/sign_up_page.html', {
        'self': self,
    })


def showWarningMessage(request, message):
    messages.info(request, message)
    self = SignUpPage.objects.get(slug='sign')
    return render(request, 'sign_up/sign_up_page.html', {
        'self': self,
    })


def verify_email(request):
    authClient = AuthClient(ApiGatewayClient())
    print("verify_email")
    email = request.POST['email-address']
    response = authClient.register("email", request.POST['email-address'])

    json = response.json()
    print("Verify email response: status: ", response.status_code, response.json())

    if (response.status_code == 200):

        messages.info(request, "An activation link has been sent to email")
        clientId = json['clientId']
        clientSecret = json['clientSecret']

        self = SignUpPage.objects.get(slug='sign')
        return render(request, 'sign_up/sign_up_page.html', {
            'self': self,
            'username': email,
            'clientId': clientId,
            'clientSecret': clientSecret,
            'visibility': "show active"
        })
    elif (response.status_code == 409 and json['code'] == 'ALREADY_EXISTS'):
        # resend verification code here
        pass
    else:
        return showErrorMessage(request, json['code'])


def continueSignup(request):
    if (request.POST['reg-type'] == 'phone'):
        user = User.objects.create_user(
            username=request.POST['phone-number'],
            email=request.POST['phone-number'],
            password=request.POST['password']
        )
        group = Group.objects.get(name='Seller')
        user.groups.add(group)
        new_user = authenticate(
            username=request.POST['phone-number'],
            password=request.POST['password'],
        )
        # call api here
        login(request, new_user)
        HttpResponseRedirect('/')
    else:
        email = request.POST['email-address']
        password = request.POST['password']
        reenterPassword = request.POST['password-reenter']
        clientId = request.POST['clientId']
        clientSecret = request.POST['clientSecret']

        if password != reenterPassword:
            return showErrorMessage(request, "password must be the same")

        authClient = AuthClient(ApiGatewayClient())
        # login account to get token for password setup
        loginResponse = authClient.login(clientId, clientSecret)

        jsonLogin = loginResponse.json()
        print("code %s - jsonLogin %s", loginResponse.status_code, jsonLogin)

        # checker for user is not confirmed
        if (loginResponse.status_code == 401 and jsonLogin['code'] == 'UNVERIFIED_LOGIN'):
            messages.error(request, "Please activate your email first")
            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/sign_up_page.html', {
                'self': self,
                'username': email,
                'clientId': clientId,
                'clientSecret': clientSecret,
                'visibility': "show active"
            })

        # TODO: validate inpunt on client side first if validateInput(email, password, reenterPassword)

        # call api here if success create a user else show necessary errors
        authClient = AuthClient(ApiGatewayClient())

        response = authClient.register("email", request.POST['email-address'])
        # TODO: Add button to resend verification link

        json = response.json()
        print(response.json())
        if (response.status_code == 200):
            json = response.json()
            response = authClient.login(json['clientId'], json['clientSecret'])

            if (response.status_code == 200):
                json = response.json()
                if (json['message'] == "User is not confirmed."):
                    return showErrorMessage(request, json['message'])

            # print("Status: %s - %s",response.status_code, response.json())

            # response = authClient.setupPassword(json['clientId'], json['clientSecret'], request.POST['password'])
            # print(response.json())
            # user = User.objects.create_user(
            #   username=request.POST['email-address'],
            #   email=request.POST['email-address'],
            #   password=request.POST['password']
            # )
            # group = Group.objects.get(name='Seller')
            # user.groups.add(group)
            # new_user = authenticate(
            #   username=request.POST['email-address'],
            #   password=request.POST['password'],
            # )

            # login success
            # ogin(request, new_user)
            return render(request, 'sign_up/sign_up_page_landing.html', {
                'request': request,
            })
        else:
            return showErrorMessage(request, json['details'])


def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a success page.
                HttpResponseRedirect('/')
            else:
                # Return an 'invalid login' error message.
                messages.error(request, 'username or password not correct')
                return HttpResponseRedirect('/')
        except ValidationError as e:
            messages.error(request, e.message)
            return HttpResponseRedirect('/')

    return HttpResponseRedirect('/')

def sign_up(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm-password']

        if not validate_email(email=username):
            messages.error(request, "Please enter a valid email address.")
            return HttpResponseRedirect('sign_up/sign_up_page.html')

        if password != confirm_password:
            messages.error(request, 'Password does not match')
            return HttpResponseRedirect('sign_up/sign_up_page.html')

        authClient = AuthClient(ApiGatewayClient())

        response = authClient.register("email", username, password)

        json = response.json()
        print("%s code", response.status_code)
        print(response.json())
        if response.status_code == 200:
            print("success: %s" % username)

            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/confirm_link.html', {
                'self': self,
                'email': username,
                'success': 'success',
                'error': ''
            })
        else:
            messages.error(request, json['details'])
            return HttpResponseRedirect('sign_up/sign_up_page.html')

    else:
        return render(request, 'sign_up/sign_up_page.html')


def resend_code(request):
    if request.method == 'POST':

        username = request.POST['username']

        if not validate_email(email=username):
            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/confirm_link.html', {
                'self': self,
                'error': "Please enter a valid email address"
            })


        authClient = AuthClient(ApiGatewayClient())

        response = authClient.resend_code(username)

        json = response.json()
        print("%s code", response.status_code)
        print(response.json())

        if response.status_code == 200:
            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/confirm_link.html', {
                'self': self,
                'email': username,
                'success': 'Email verification link sent',
                'error': ''
            })
        elif response.status_code == 400:
            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/confirm_link.html', {
                'self': self,
                'email': username,
                'confirmed': "Email already confirmed.",
                'error': ''
            })

        elif response.status_code == 500:

            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/confirm_link.html', {
                'self': self,
                'email': username,
                'error': "You're trying to send activation links too fast. Please try again later."
            })

        else:

            self = SignUpPage.objects.get(slug='sign')
            return render(request, 'sign_up/confirm_link.html', {
                'self': self,
                'email': username,
                'error': "Email does not exist"
            })


    pass
def signUpWithEmail(request):
    username = request.POST['username']
    password = request.POST['password']

sign_up/templates/sign_up/includes/by_email.html
{% load static %}
{% load wagtailcore_tags wagtailimages_tags wagtailimages_tags %}

<div class="tab-pane fade show active" id="verify_email">
    <div class="form-wrap">
        <form class="hidden" action="/sign/verify_email/" method="POST">
            {% csrf_token %}
            <div class="row">
                <input type="hidden" id="reg-type" name="reg-type" value="email">
                <div class="col-md-9">
                    <input type="email" name="email-address" class="form-control" placeholder="Email Address" required="" id="id_email-address" value="{{username}}">
                </div>
                <div class="col-md-3">
                    <button type="submit" name="verify-email" class="btn btn-success float-right">Send Email Verification</button>
                </div>
            </div>
        </form>
        <form action="/sign/sign_up/" method="POST">
                {% csrf_token %}
                <div class="row">
                    <input type="hidden" id="reg-type" name="reg-type" value="email">
                    <input type="text" id="clientId" name="clientId" value="{{clientId}}">
                    <input type="text" id="clientSecret" name="clientSecret" value="{{clientSecret}}">
                    <div class="col-md-12">
                        <input type="hidden" name="email-address" class="form-control" placeholder="Email Address" required="" id="id_email-address" value = "{{username}}">
                    </div>

                    <div class="col-md-12">
                        <input type="password" name="password" class="form-control" placeholder="Password" required="" id="id_password">
                    </div>
                    <div class="col-md-12">
                        <input type="password" name="password-reenter" class="form-control" placeholder="Re-Enter Password" required="" id="id_password_reenter">
                    </div>
                    <div class="agreement-checkbox col-md-1">
                        <input type="checkbox" name="agreement" class="form-control" required="" id="id_agreement"> 
                    </div>
                    <div class="col-md-11">
                        <p> I've read and understood <a href="https://drive.google.com/file/d/16-XqTcR36j4bEwamFal6wWcv5kwp8Ga1/view?spm=a2a1n.12768535.old-navigation.2.25201e13HAoNIP">Seller Center's Marketplace Agreement</a></p>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success submit-button float-right">submit</button>
                    </div>
                </div>
            </form>
    </div>
</div>

sign_up/templates/sign_up/includes/by_phone_number.html
{% load static %}
{% load wagtailcore_tags wagtailimages_tags wagtailimages_tags %}

<div class="tab-pane fade" id="phone">
    <div class="form-wrap">
        <form action=" {{ page.url }}" method="POST">
            {% csrf_token %}
            <div class="row">
                <input type="hidden" id="reg-type" name="reg-type" value="phone">
                <div class="col-md-9">
                    <input type="text" name="phone-number" class="form-control" placeholder="Phone Number" required="" id="id_phone-number">
                </div>
                <div class="col-md-3">
                    <button type="button" class="btn btn-success float-right">Send Verification Code</button>
                </div>
                <div class="col-md-12">
                    <input type="text" name="otp" class="form-control" placeholder="Verification Code" required="" id="id_otp">
                </div>  
                <div class="col-md-12">
                    <input type="password" name="password" class="form-control" placeholder="Password" required="" id="id_password">
                </div>
                <div class="col-md-12">
                    <input type="password" name="password-reenter" class="form-control" placeholder="Re-Enter Password" required="" id="id_password_reenter">
                </div>
                
                <!-- <div class="col-md-12">
                    <p>Account Type</p>
                    <ul id="id_account-type">
                        <li><label for="id_account-type_0"><input type="radio" name="account-type" value="Individual" placeholder="Account Type" required="" id="id_account-type_0" checked="">
                            Individual
                        </label></li>
                        <li><label for="id_account-type_1"><input type="radio" name="account-type" value="Corporate" placeholder="Account Type" required="" id="id_account-type_1">
                            Corporate
                        </label></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <p>Country</p>
                    <ul id="id_country">
                        <li><label for="id_country_0"><input type="radio" name="country" value="Philippines" placeholder="Account Type" required="" id="id_country_0" checked="">
                            Philippines
                        </label></li>
                    </ul>
                </div> -->
                <div class="agreement-checkbox col-md-1">
                    <input type="checkbox" name="agreement" class="form-control" required="" id="id_agreement"> 
                </div>
                <div class="col-md-11">
                    <p> I've read and understood <a href="https://drive.google.com/file/d/16-XqTcR36j4bEwamFal6wWcv5kwp8Ga1/view?spm=a2a1n.12768535.old-navigation.2.25201e13HAoNIP">Seller Center's Marketplace Agreement</a></p>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-success submit-button float-right">submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

sign_up/templates/sign_up/includes/reset_password_by_email.html
{% load static %}
{% load wagtailcore_tags wagtailimages_tags wagtailimages_tags %}

<div class="tab-pane fade show active" id="email">
    <div class="form-wrap">
        <form action="{{page.url}}" method="POST">
            {% csrf_token %}
            <div class="row">
                <input type="hidden" id="reg-type" name="reg-type" value="email">
                <div class="col-md-9">
                    <input type="email" name="email-address" class="form-control" placeholder="Email Address" required="" id="id_email-address">
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-success button-submit float-right">Send One-Time-Password</button>
                </div>
            </div>
        </form>
    </div>
</div>

sign_up/templates/sign_up/includes/reset_password_by_phone_number.html
{% load static %}
{% load wagtailcore_tags wagtailimages_tags wagtailimages_tags %}

<div class="tab-pane fade" id="phone">
    <div class="form-wrap">
        <form action="{{page.url}}" method="POST">
            {% csrf_token %}
            <div class="row">
                <input type="hidden" id="reg-type" name="reg-type" value="phone">
                <div class="col-md-9">
                    <input type="text" name="phone-number" class="form-control" placeholder="Phone Number" required="" id="id_phone-number">
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-success button-submit float-right">Send One-Time-Password</button>
                </div>
            </div>
        </form>
    </div>
</div>

sign_up/templates/sign_up/includes/reset_password_filter.html
<div class="reset-password-filters">
    <div class="container">
        <ul class="nav" id="nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#email" role="tab">By Email</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#phone" role="tab">By Phone</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/admin/login">Log In Instead</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

sign_up/templates/sign_up/includes/sign_up_filter.html
<div class="sign-up-filters">
    <div class="container">
        <ul class="nav" id="nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#email" role="tab">By Email</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#phone" role="tab">By Phone</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin/login">Log In Instead</a>
            </li>
        </ul>
    </div>
</div>